---
container_manager_on_localhost: docker
# Please see roles/container-engine/containerd/defaults/main.yml for more configuration options
# Container for runtime
container_manager: containerd.io
containerd_use_systemd_cgroup: true
runc_bin_dir: /usr/bin
containerd_bin_dir: /usr/bin
