---
cri_socket: /var/run/containerd/containerd.sock
containerd_bin_dir: /usr/bin
bin_dir: /opt/bin

containerd_use_systemd_cgroup: true
containerd_state_dir: /run/containerd
containerd_metrics_grpc_histogram: true
containerd_metrics_address: "127.0.0.1:1338"

containerd_debug_level: 'info'
# containerd_default_runtime: "runc"
containerd_snapshotter: "overlayfs"
pod_infra_image_repo:
pod_infra_image_tag:
containerd_runc_runtime:
  name: runc
  type: "io.containerd.runc.v2"
  engine: ""
  root: ""
  base_runtime_spec: cri-base.json
  options:
    systemdCgroup: "{{ containerd_use_systemd_cgroup | ternary('true', 'false') }}"
containerd_additional_runtimes: []

containerd_base_runtime_spec_rlimit_nofile: 65535

containerd_default_base_runtime_spec_patch:
  process:
    rlimits:
      - type: RLIMIT_NOFILE
        hard: "{{ containerd_base_runtime_spec_rlimit_nofile }}"
        soft: "{{ containerd_base_runtime_spec_rlimit_nofile }}"

containerd_base_runtime_specs:
  cri-base.json: "{{ containerd_default_base_runtime_spec | combine(containerd_default_base_runtime_spec_patch,recursive=1) }}"


containerd_grpc_max_recv_message_size: 16777216
containerd_grpc_max_send_message_size: 16777216
cri_auths: {}
containerd_registries:
  "docker.io": "https://registry-1.docker.io"

containerd_max_container_log_line_size: -1

containerd_cfg_dir: /etc/containerd
