---
- debug:
    msg: "{{resolvfile}} - {{ resolvconf_kubelet}}"

- name: Add domain/search/nameservers/options to resolv.conf
  blockinfile:
    path: "{{ resolvfile }}"
    block: |-
      {% for item in searchentries|d([]) + namesrvs -%}
      {{ item }}
      {% endfor %}
      options ndots:{{ ndots }} timeout:2 attempts:2 edns
    state: present
    insertbefore: BOF
    create: yes
    backup: yes
    marker: "# Ansible entries {mark}"
    mode: 0644
  notify: Preinstall | propagate resolvconf to k8s components
