- name: generate symlink to certs
  ansible.builtin.file:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    state: link
  loop:
    - src: "{{etcd_cert_paths.client.ca}}"
      dest: "{{kube_etcd_cacert_file}}"
    - src: "{{etcd_cert_paths.client.cert}}"
      dest: "{{kube_etcd_cert_file}}"
      dest: "{{etcd_cert_dir}}/kube-client-cert.pem"
    - src: "{{etcd_cert_paths.client.key}}"
      dest: "{{kube_etcd_key_file}}"
  when:
    - inventory_hostname  in groups['kube_control_plane']
