---
- hosts: kube_control_plane
  strategy: linear
  any_errors_fatal: true
  tasks:
    - import_role:
        name: etcd3/facts
      vars:
        etcd_cluster_name: k8s
        etcd_ports:
            client: 2379
            peer: 2380
      tags:
         - etcd
         - etcd-facts

- hosts: kube_control_plane
  strategy: linear
  any_errors_fatal: true
  tasks:
    - import_role:
        name: etcd3/facts
      vars:
        etcd_cluster_name: k8s-events
        etcd_ports:
            client: 2381
            peer: 2382
      tags:
         - etcd
         - etcd-facts

- name: Gather facts
  hosts: cluster-all:etcd:calico_rr
  gather_facts: False
  tags: always
  tasks:
    - name: Gather and compute network facts
      import_role:
        name: network_facts

    - name: Gather minimal facts
      setup:
        gather_subset: '!all'

    # filter match the following variables:
    # ansible_default_ipv4
    # ansible_default_ipv6
    # ansible_all_ipv4_addresses
    # ansible_all_ipv6_addresses
    - name: Gather necessary facts (network)
      setup:
        gather_subset: '!all,!min,network'
        filter: "ansible_*_ipv[46]*"

    # filter match the following variables:
    # ansible_memtotal_mb
    # ansible_swaptotal_mb
    - name: Gather necessary facts (hardware)
      setup:
        gather_subset: '!all,!min,hardware'
        filter: "ansible_*total_mb"
