---
# Locally configure bastion-ssh
- hosts: bastion[0]
  gather_facts: false
  tasks:
    - include_role:
        name: bastion-ssh-config
      tags:
        - bastion
      vars:
        ansible_connection: local
