---
- hosts: k8s_cluster
  strategy: free
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: network_facts, tags: facts}
    - { role: etcd3/facts, tags: preinstall, facts}
    - { role: kubespray_defaults, tags: facts}
    - { role: microspray-defaults, tags: facts}
    - { role: kubernetes/microspray-preinstall, tags: preinstall}
    - { role: download, tags: download, when: "not skip_downloads" }
    - { role: kubernetes/node, tags: node }
