---
- hosts: kube_control_plane
  gather_facts: true
  strategy: linear
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - role: etcd3/facts
      vars:
        etcd_cluster_name: k8s-events
        etcd_ports:
            client: 2381
            peer: 2382
      tags:
         - etcd
         - etcd-facts
         - facts
    - role: etcd3/facts
      vars:
        etcd_cluster_name: k8s
        etcd_ports:
            client: 2379
            peer: 2380
      tags:
         - etcd
         - etcd-facts
         - facts
    - { role: kubespray-defaults, tags: facts}
    - { role: microspray-defaults, tags: facts}
    - { role: kubernetes/node, tags: node }
    - { role: kubernetes/microspray-control-plane, tags: master }
    - { role: kubernetes/client, tags: client }
    - { role: kubernetes-apps/cluster_roles, tags: cluster-roles }
    # - { role: kubernetes-apps/rotate_tokens, tags: rotate_tokens, when: "secret_changed|default(false)" }
