---

- hosts: kube_node
  gather_facts: true
  strategy: linear
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray-defaults, tags: facts}
    - { role: microspray-defaults, tags: facts}
    - { role: etcd3/facts, tags: facts }

# Installed after via applications
#    - { role: network_plugin, tags: network }
    - role: kubernetes/kubeadm-add-node
      tags: kubeadm
      vars:
        kube_control_plane: "{{groups['kube_control_plane'][0]}}"
