---

- hosts: kube_node
  gather_facts: true
  strategy: linear
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"

  roles:
    - { role: network_facts, tags: facts}
    - { role: kubespray_defaults, tags: facts}
    - { role: microspray-defaults, tags: facts}
    - { role: network_facts, tags: facts}
    - role: etcd3/facts
      vars:
        etcd_cluster_name: k8s-events
      tags:
         - etcd
         - etcd-facts
         - facts
    - role: etcd3/facts
      vars:
        etcd_cluster_name: k8s
      tags:
         - etcd
         - etcd-facts
         - facts    
    - { role: kubernetes/kubeadm, tags: kubeadm }
    - { role: kubernetes/node-label, tags: node-label }
    - { role: kubernetes/microspray-node-taint, tags: node-taint }
         

# # Installed after via applications
# #    - { role: network_plugin, tags: network }
#     - role: kubernetes/kubeadm-add-node
#       tags: kubeadm
#       vars:
#         kube_control_plane: "{{groups['kube_control_plane'][0]}}"
