- hosts: kube_control_plane[0]
  gather_facts: true
  strategy: linear
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray-defaults, tags: facts}
    - { role: microspray-defaults, tags: facts}
    - { role: kubernetes-apps, tags: [apps] }
#    - { role: kubernetes-apps/network_plugin, tags: network }
    # - { role: kubernetes-apps/policy_controller, tags: policy-controller }
    # - { role: kubernetes-apps/ingress_controller, tags: ingress-controller }
    # - { role: kubernetes-apps/external_provisioner, tags: external-provisioner }
