---

- hosts: kube_control_plane
  strategy: linear
  serial: 1
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: network_facts, tags: facts}
    - { role: kubespray_defaults, tags: facts}
    - { role: microspray-defaults, tags: facts}
    - { role: network_facts, tags: facts}
    - {role: etcd3/facts, vars: {etcd_cluster_name: k8s-events}, tags: facts}
    - {role: etcd3/facts, vars: {etcd_cluster_name: k8s}, tags: facts}
    - { role: kubernetes/microspray-preinstall, tags: preinstall}
    - { role: download, tags: download, when: "not skip_downloads" }    
    - { role: kubernetes/node, tags: node }
    - { role: kubernetes/control-plane, tags: control-plane, upgrade_cluster_setup: true }         

- hosts: kube_node
  strategy: free
  serial: "{{ serial | int | default('2')}} "
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: network_facts, tags: facts}
    - { role: kubespray_defaults, tags: facts}
    - { role: microspray-defaults, tags: facts}
    - { role: network_facts, tags: facts}
    - {role: etcd3/facts, vars: {etcd_cluster_name: k8s-events}, tags: facts}
    - {role: etcd3/facts, vars: {etcd_cluster_name: k8s}, tags: facts}
    - { role: kubernetes/microspray-preinstall, tags: preinstall}
    - { role: download, tags: download, when: "not skip_downloads" }    
    - { role: kubernetes/node, tags: node }
    - { role: kubernetes/kubeadm, tags: kubeadm }
